// <auto-generated />
namespace actively.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207172231468_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOVZzXLbNhC+d6bvwOE9oqX8jOuhknEkO+OpZXtCJYfeIHIlcQoCLAG60rP10EfqK3TBX5CiKNKSnaS9eKwl9ttdYHfxcfnPX3/bHzYBNR4hEj5nY3M4ODMNYC73fLYam7Fcvjo3P7z/+Sf7ygs2xtd83Wu1DjWZGJtrKcMLyxLuGgIiBoHvRlzwpRy4PLCIx63R2dkv1nBoAUKYiGUY9ueYST+A5Af+nHDmQihjQmfcAyoyOT5xElTjjgQgQuLC2CSu9B+BbgfpUtO4pD5BNxygS9MI31x8EeDIiLOVExLpEzrfhoDPl4QKyJy+CN909ftspPy2CGNcIhxnT4rbLCLCmK4wdrlVbiVxjc1b7qbQ2ipc9ytsKwIUPUQ8hEhuP8My073xTMOq6ll1xUJN01Hm8T8mX49M4y6mlCwoFLuE2+hIHsEnYBARCd4DkRIipnQhcX/Has2G+ptbwePAdDKNa38D3i2wlVwXlmZkk0uGo3PT+MJ8zD5UklEMumfp73ajE84jzFx0WOS2PwFfRSRcb/tiXXpeBEK8fAzJ5r6wUQdzu+9xqcQ5yugDF5LQvrG+O9KqstbT5ujtsUaxIv/E1OybTW+H/fbYtsre0tpx0q2fIOx/qed8m4T6/xTsLZG5ySmPUa3hFA8gcOXnURBz5A2/cQaH0qkdZerM+wC0FxbSF0l8zNr86sgoipLDRtZKLNVxQNZuf2wOpZGUzwwKZlAPpw6Spr462iYYrdwbwyoCKImXlTKvnKFZeyiaPSNhiMmnUbZMYjgpX5u8cvpTpiDFsFzRwJwKbwtL2DbICmpPFR3w4NqPhJwSSRZEHerEC3aWdTyu3Fr91Or9stz9XEP9n2rVyOugmfnp23iNkQXY/pIgoXBmH2nMlB2XUBI1tOAJp3HA9rXxNu2U0On6qaQ7QoWd6UCVB93xCoamYxXCHn4lDbziUMNl04aQdWMdIhN1x8gvLx0kl3VHSdmNjpFK"
                       + "uiOUVEVHKaW7SLZVy9V6RVg7JVEjD/Ua61SBess7pgb3caEE6FAVtik/Tx2eJk++j5xPCIWOkAh66Cd0ogKQSHrUS8EmKjVTSLsjJYxCB0kEL1wtOxd6fUlhvbjYaxe4nV2mhwcxO7drusQ0cGMefU/drM5WSAgGasHA+YNOqI/xlgtmhPlLEHLOfwek+Xj5n9fGOU8YtVhCePR7nbf4KvyDbzk9uaw+amGPJHLXJNp93Th6krI60STlZC5q712nwqy8VjWCVl8V+o85mj19d8wUoxEymVkcN6RoxE1GEj/8DOJZ6vBZDvpHyXJtNrCkXP04YjTwNIT6ZCA55KfPBQ6r95sK7L6NdpsLtI4F0jt3bHoLjn6nnmoDhU5Tg3Qu0Do0aDJTPhfN29JhqrBLNmxL/zZkT0H4qxJCfSli4KroStB8zQ1b8vw4MUbdo3xJ7bRnIImHp3EZSX+J7wX42MWbKhmmfSU0xiVXwQK8G3YfyzCWl0JAsKAVnmxb7faT0UnVZ/s+TM7nFCGgmz6GAPfsY+xTr/D7uiFd90CoI8zaIHrlSNUOV9sC6W6HCO8DyrZvCiEw1UTnEIRUUYh75pBH2O/b4T2s7pg99QlykUBkGKW++lRpqW+V7/8FzW74Zt0cAAA="; }
        }
    }
}
